version: "3"

volumes:
  db-data:
  es-data:

networks:
  frontend:
  backend:
    internal: true

services:
  postgres:
    image: postgres:11.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./00-createdb.sql:/docker-entrypoint-initdb.d/00-createdb.sql
    networks:
      - backend
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./dictionaries:/usr/share/elasticsearch/config/hunspell
    networks:
      - backend
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    restart: always
  mdg:
    image: akashihi/mdg:next
    networks:
      - backend
    environment:
      - APPLICATION_SECRET=composer
    restart: always
    depends_on:
      - postgres
  rates:
    image: akashihi/mdg-rate-loader:next
    networks:
      - backend
      - frontend
    restart: always
    depends_on:
      - postgres
  ui:
    image: akashihi/mdg-web-ui:next
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - mdg